modLoader="javafml" 
loaderVersion="[47,)" 
license="MIT"
[[mods]] 
    modId="cutscene_api" 
    version="${file.jarVersion}" 
    displayName="Cutscene API" 
    logoFile="examplemod.png" 
    authors="TheWinNT"
    description='''
        A Minecraft mod that adds cutscene mechanics to the game. Can be useful for map makers and mod developers
    '''
    displayURL="https://github.com/thewinnt/Cutscene-API-Forge"

[[dependencies.cutscene_api]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
